global:
  scrape_interval: "6s"

scrape_configs:
  - job_name: "job_platform_api"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8080"]
        labels:
          application: "job_platform_api"